name: "Deploy storage-automation logic-app"

on:
  workflow_dispatch:
    inputs:
      storagesResourceGroupName:
        description: "storages resource group name"
        required: true

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@main
      
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ inputs.storagesResourceGroupName }}
        template: ./templates/logic-app-templates/template.json
        parameters: |
          frequency="Week"
          interval=1
          location="westeurope"
          sites_func_get_last_fetch_time_for_each_storage_account_externalid="/subscriptions/${{ secrets.AZURE_SUBSCRIPTION }}/resourceGroups/${{ inputs.storagesResourceGroupName }}/providers/Microsoft.Web/sites/func-three-01"
          sites_func_get_storage_list_by_subscription_externalid="/subscriptions/${{ secrets.AZURE_SUBSCRIPTION }}/resourceGroups/${{ inputs.storagesResourceGroupName }}/providers/Microsoft.Web/sites/func-three-02"
          sites_func_get_subscription_list_externalid="/subscriptions/${{ secrets.AZURE_SUBSCRIPTION }}/resourceGroups/${{ inputs.storagesResourceGroupName }}/providers/Microsoft.Web/sites/func-three-03"
          sites_func_sending_excel_by_email_and_mark_storages_for_deletion_externalid="/subscriptions/${{ secrets.AZURE_SUBSCRIPTION }}/resourceGroups/${{ inputs.storagesResourceGroupName }}/providers/Microsoft.Web/sites/func-three-04"
          sites_func_check_storage_externalid="/subscriptions/${{ secrets.AZURE_SUBSCRIPTION }}/resourceGroups/${{ inputs.storagesResourceGroupName }}/providers/Microsoft.Web/sites/func-three-05"
          workflows_logic_app_name="logic-app-try"
